# Generated by Django 4.2 on 2024-10-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category_post_notification_comments_bookmark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="views",
            new_name="view",
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("Like", "Like"),
                    ("Comment", "Comment"),
                    ("Bookmark", "Bookmark"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Disabled", "Disabled"),
                    ("Active", "Active"),
                ],
                default="Active",
                max_length=100,
            ),
        ),
    ]
